version: "3.9"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    container_name: flask-backend
    restart: always
    volumes:
      - ./backend/logs:/app/logs

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    container_name: react-frontend
    restart: always
    depends_on:
      - backend
