- name: Deploy all services using Docker Compose
  hosts: local
  become: true
  tasks:
    - name: Stop all running containers (optional cleanup)
      shell: docker-compose -f docker-compose.yml down
      args:
        chdir: "{{ playbook_dir }}"

    - name: Start all services with Docker Compose
      shell: docker-compose -f docker-compose.yml up -d --build
      args:
        chdir: "{{ playbook_dir }}"