- name: Deploy Flask backend and React frontend locally
  hosts: local
  become: false
  tasks:

    - name: Stop and remove existing backend container
      shell: |
        docker rm -f flask-backend || true

    - name: Stop and remove existing frontend container
      shell: |
        docker rm -f react-frontend || true

    - name: Build Flask backend Docker image
      shell: |
        docker build -t flask-backend ./backend

    - name: Build React frontend Docker image
      shell: |
        docker build -t react-frontend ./frontend

    - name: Run Flask backend container
      shell: |
        docker run -d --name flask-backend -p 5000:5000 flask-backend

    - name: Run React frontend container
      shell: |
        docker run -d --name react-frontend -p 3000:80 react-frontend
