# -*- coding: utf-8 -*-
"""SPE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ynWV1Yyx8BpiiwMgvkS53KjXVo5pCLAw
"""

# %%
import pandas as pd
import re

# Load the dataset
df = pd.read_csv('all_tickets_processed_improved_v3.csv')

# %%
len(df)

# %%
df['Topic_group'].unique()

# %%
df.dropna(inplace=True)

def clean_text(text):
    text = text.lower()
    text = re.sub(r'\W', ' ', text)
    text = re.sub(r'\s+', ' ', text)
    return text.strip()

# Apply text cleaning
df['cleaned_document'] = df['Document'].apply(clean_text)

# %%
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(max_features=1000)
X = tfidf.fit_transform(df['cleaned_document']).toarray()

# %%
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y = le.fit_transform(df['Topic_group'])

# %%
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# %%
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

# %%
from sklearn.metrics import accuracy_score, classification_report

y_pred = model.predict(X_test)
print(f'Accuracy: {accuracy_score(y_test, y_pred)}')
print(classification_report(y_test, y_pred, target_names=le.classes_))

# %%
import joblib

joblib.dump(model, 'ticket_classification_model.pkl')
joblib.dump(tfidf, 'tfidf_vectorizer.pkl')

