FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY retrain.py .
COPY model_script.py .
COPY all_tickets_processed_improved_v3.csv .

RUN mkdir -p logs

CMD ["python", "-u", "retrain.py"]
